# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            jlc
tagline:          'jimmylocoding'
description:      'jimmylocoding'
url:              http://jimmylocoding.com
shorturl:					jimmylocoding.com
baseurl:          /
imageurl:         '/images/'

author:
  name:           'Jimmy Lo'
  url:            http://jimmylorunning.com

paginate:         5

# Custom vars
version:          2.1.0

disqusid:         'jimmylocoding'

social:
  github:         https://github.com/jimmylorunning
  twitter:        http://twitter.com/jimmylocoding
