# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            jlc
tagline:          'Tagline'
description:      'jimmylocoding'
url:              http://jimmylorunning.github.io/blog
baseurl:          /

author:
  name:           'Jimmy Lo'
  url:            http://jimmylocoding.com

paginate:         5

# Custom vars
version:          2.1.0

social:
  github:         https://github.com/jimmylorunning